- name: "Creating Resource Group: {{ name }}"
  azure_rm_resourcegroup: name={{ name }} state=present location={{ region }}
                          tags={{ labels }}
                          subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                          client_id={{ azure_client_id }} secret={{ azure_secret }}
  ignore_errors: True
  tags: [ ocp, azure, resource_group ]

- name: "Creating Network VNET for OpenShift (aka VPC): {{ network_openshift_address_prefix }}"
  azure_rm_virtualnetwork: name={{ name }} state=present
                           resource_group={{ name }} location={{ region }}
                           address_prefixes={{ network_openshift_address_prefix }}
                           tags={{ labels }}
                           subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                           client_id={{ azure_client_id }} secret={{ azure_secret }}
  tags: [ ocp, azure, network ]

- name: "Creating Subnet {{ name }}-master-infra for Master and infra: {{ network_subnet_openshift_master_prefix }}"
  azure_rm_subnet: name="{{ name }}-master-infra" state=present
                   resource_group={{ name }}
                   virtual_network_name={{ name }} 
                   address_prefix_cidr={{ network_subnet_openshift_master_prefix }}
                   tags={{ labels }}
                   subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                   client_id={{ azure_client_id }} secret={{ azure_secret }}
  tags: [ ocp, azure, network ]

- name: "NODE: Creating Subnet {{ name }}-node for Application Nodes: {{ network_subnet_openshift_node_prefix }}"
  azure_rm_subnet: name="{{ name }}-node" state=present
                   resource_group={{ name }}
                   virtual_network_name={{ name }}
                   address_prefix_cidr={{ network_subnet_openshift_node_prefix }}
                   tags={{ labels }}
                   subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                   client_id={{ azure_client_id }} secret={{ azure_secret }}
  tags: [ ocp, azure, network ]

- name: "MASTER: Creating Network Security Group (aka SG): {{ name }}-master-sg"
  azure_rm_securitygroup: name="{{ name }}-master-sg" state=present
                          resource_group={{ name }} location={{ region }}
                          rules={{ network_security_group_master }}
                          tags={{ labels }}
                          subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                          client_id={{ azure_client_id }} secret={{ azure_secret }}
  tags: [ ocp, azure, network ]

- name: "INFRA: Creating Network Security Group (aka SG): {{ name }}-infra-sg"
  azure_rm_securitygroup: name="{{ name }}-infra-sg" state=present
                          resource_group={{ name }} location={{ region }}
                          rules={{ network_security_group_infra }}
                          tags={{ labels }}
                          subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                          client_id={{ azure_client_id }} secret={{ azure_secret }}
  tags: [ ocp, azure, network ]

- name: "NODE: Creating Network Security Group (aka SG): {{ name }}-node-sg"
  azure_rm_securitygroup: name="{{ name }}-node-sg" state=present
                          resource_group={{ name }} location={{ region }}
                          rules={{ network_security_group_node }}
                          tags={{ labels }}
                          subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                          client_id={{ azure_client_id }} secret={{ azure_secret }}
  tags: [ ocp, azure, network ]

- name: "BASTION: Creating Network Security Group (aka SG): {{ name }}-bastion-sg"
  azure_rm_securitygroup: name="{{ name }}-bastion-sg" state=present
                          resource_group={{ name }} location={{ region }}
                          rules={{ network_security_group_bastion }}
                          tags={{ labels }}
                          subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                          client_id={{ azure_client_id }} secret={{ azure_secret }}
  tags: [ ocp, azure, network, bastion ]
