- name: STOPPING Bastion
  azure_rm_virtualmachine: name={{ bastion_definition.hostname }} location={{ region }}
                           state=present started=False allocated=False
                           resource_group={{ name }}
                           tags={{ labels }}
                           subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                           client_id={{ azure_client_id }} secret={{ azure_secret }}

- name: STOPPING OpenShift Cluster
  azure_rm_virtualmachine: name={{ item.hostname }} location={{ region }} 
                           state=present started=False allocated=False
                           resource_group={{ name }}
                           tags={{ labels }}
                           subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                           client_id={{ azure_client_id }} secret={{ azure_secret }}
  with_items: "{{ master_definition }}+{{ infra_definition }}+{{ node_definition }}"
